# Generated by Django 5.2.9 on 2025-12-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
