# Generated by Django 5.2.9 on 2025-12-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hello_message',
            field=models.BooleanField(default=False),
        ),
    ]
