# Generated by Django 5.2.9 on 2025-12-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_user_hello_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='...', max_length=150),
        ),
    ]
