# Generated by Django 5.2.9 on 2025-12-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0004_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
